### ISSUE TITLE
Cannot run on Ubuntu 18.10

### ISSUE THREAD

**Issue by alwzying** [anetczuk/ClevoKeyboardControl#1]
sudo python3 '/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/main.py' 

2018-12-16 22:04:40,929 DEBUG    MainThread __main__:main [main.py:85] Starting the application
2018-12-16 22:04:40,929 DEBUG    MainThread __main__:main [main.py:86] Logger log file: /home/raigo/log.txt
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
2018-12-16 22:04:40,978 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:42] starting suspension detector
2018-12-16 22:04:40,979 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:121] starting suspension detector
2018-12-16 22:04:40,982 DEBUG    MainThread clevokeyboardcontrol.gui.main_window:setIconTheme [main_window.py:97] setting tray theme: <TrayIconTheme.WHITE: 'keyboard-white.png'>
2018-12-16 22:04:40,987 DEBUG    MainThread clevokeyboardcontrol.gui.driver_widget:attachDriver [driver_widget.py:74] attaching driver
2018-12-16 22:04:41,1   DEBUG    MainThread clevokeyboardcontrol.gui.main_window:loadSettings [main_window.py:60] loading app state from /home/raigo/.config/arnet/ClevoKeyboardControl.ini
2018-12-16 22:04:41,2   WARNING  MainThread clevokeyboardcontrol.gui.settings_widget:_setCurrentTrayTheme [settings_widget.py:146] could not find index for theme: ''
2018-12-16 22:04:41,2   ERROR    MainThread __main__:main [main.py:105] Exception occured
Traceback (most recent call last):
  File "/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/main.py", line 101, in main
    exitCode = runApp(args)
  File "/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/main.py", line 61, in runApp
    window.loadSettings()
  File "/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/gui/main_window.py", line 61, in loadSettings
    self.ui.settingsWidget.loadSettings( settings )
  File "/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/gui/settings_widget.py", line 101, in loadSettings
    self._emitDriverRestore( restoreStartValue )
  File "/home/raigo/下载/ClevoKeyboardControl-master/src/clevokeyboardcontrol/gui/settings_widget.py", line 152, in _emitDriverRestore
    self.restoreDriver.emit( self.driverState )
TypeError: SettingsWidget.restoreDriver[dict].emit(): argument 1 has unexpected type 'NoneType'

2018-12-16 22:04:41,3   INFO     MainThread __main__:main [main.py:121] Execution time:   73.65441322ms

**Comment by anetczuk** [comment]
Thanks for issue. Fixed, try new code

**Comment by alwzying** [comment]
Now it can be launched with `python3 main.py`, but when execute clevobdctl, still got error:
`sh '/opt/ClevoKeyboardControl-master/src/clevokbdctl' 
/opt/ClevoKeyboardControl-master/src/clevokbdctl: 6: /opt/ClevoKeyboardControl-master/src/clevokbdctl: Bad substitution
/usr/bin/python3: No module named clevokeyboardcontrol
` 
ps:I copied the dir to /opt

**Comment by anetczuk** [comment]
Script `clevobdctl` meant to be run under `bash` shell. Fixed for `sh`. Try new code.
