### ISSUE TITLE
Can't launch on 21.04

### ISSUE THREAD

**Issue by giovannicaligaris** [anetczuk/ClevoKeyboardControl#3]
I know this is still a testing version but this is the error I am getting.

```
$ ./clevokbdctl 

2021-09-08 01:11:03,553 DEBUG    MainThread clevokeyboardcontrol.main:main [main.py:85] Starting the application
2021-09-08 01:11:03,553 DEBUG    MainThread clevokeyboardcontrol.main:main [main.py:86] Logger log file: /home/user/ClevoKeyboardControl/src/log.txt
2021-09-08 01:11:03,749 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:setEnabled [suspenddetector.py:127] changing suspend detector state to True
2021-09-08 01:11:03,749 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:134] starting suspension detector
2021-09-08 01:11:03,750 DEBUG    MainThread clevokeyboardcontrol.gui.suspenddetector:start [suspenddetector.py:42] starting suspension timer
2021-09-08 01:11:03,750 DEBUG    MainThread clevokeyboardcontrol.screensaverwatcher.ScreenSaverWatcher:__init__ [screensaverwatcher.py:131] registering device watcher: /sys/class/backlight/amdgpu_bl0
2021-09-08 01:11:03,751 ERROR    MainThread clevokeyboardcontrol.main:main [main.py:105] Exception occured
Traceback (most recent call last):
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/main.py", line 101, in main
    exitCode = runApp(args)
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/main.py", line 59, in runApp
    window = MainWindow( driver )
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/gui/main_window.py", line 68, in __init__
    self.screenSaverDetector = screensaverwatcher.ScreenSaverWatcher()
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/screensaverwatcher.py", line 132, in __init__
    watcher = DeviceWatcher( item_path, len(self.watchers) )
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/screensaverwatcher.py", line 63, in __init__
    self.watcher.watch( self.driverPath, False )
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/sysfswatchdog.py", line 63, in watch
    self.observer.start()
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/usr/lib/python3/dist-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 76, in on_thread_start
    self._snapshot = self._take_snapshot()
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 72, in <lambda>
    self._take_snapshot = lambda: DirectorySnapshot(
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 247, in __init__
    st = self.stat(path)
  File "/home/user/ClevoKeyboardControl/src/clevokeyboardcontrol/sysfswatchdog.py", line 151, in stat
    return polling.default_stat(path)
AttributeError: module 'watchdog.observers.polling' has no attribute 'default_stat'

2021-09-08 01:11:03,752 INFO     MainThread clevokeyboardcontrol.main:main [main.py:121] Execution time:  199.56254959ms
```

**Comment by anetczuk** [comment]
Hello, thanks for issue.
It seems You have unsupported (too new) version of watchdog.
Please show me output of `pip show watchdog`. My version is 0.9.0.

**Comment by giovannicaligaris** [comment]
```
$ sudo apt-cache policy python3-watchdog 
python3-watchdog:
  Installed: 1.0.2-2
  Candidate: 1.0.2-2
  Version table:
 *** 1.0.2-2 500
        500 http://gb.archive.ubuntu.com/ubuntu impish/universe amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu impish/universe i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by giovannicaligaris** [comment]
Downgrading to 0.9.0 fixes the issue, but it should probably be upgraded to 1.0 sometime soon.

sudo pip3 install watchdog==0.9.0

**Comment by anetczuk** [comment]
Thanks for information. I was suspecting that there are incompatibilities between versions. Will try to update and add condition to watchdog's old API.

**Comment by anetczuk** [comment]
Reviewed the code and found universal solution (hopefully). Please check if you still have the problem (with your recent/default watchdog version).

**Comment by giovannicaligaris** [comment]
I removed watchdog==0.9.0 and installed python3-watchdog and recompiled everything, works well now
